<section class="b-section b-section-rules">
    <div class="b-section-header layout w976px">
        <div class="b-section-header-iname">ОФІЦІЙНІ УМОВИ</div>
    </div>
    <div class="b-section-body layout w976px b-rules">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse rutrum ullamcorper quam eget dictum. Aliquam a magna ante. Aenean sed justo euismod lacus sodales blandit vel sed massa. Nam eu libero sit amet nibh suscipit pharetra a ac ligula. Integer nec nibh sed lectus adipiscing convallis. Sed interdum imperdiet mattis. Pellentesque molestie dui sit amet odio hendrerit id commodo lorem dignissim. Vestibulum ac neque erat, vel fermentum sapien. Sed eleifend iaculis sem non dictum. Cras nibh erat, placerat ut cursus ac, lacinia quis purus. Proin nec mauris mauris.</p>
        <p>Aliquam quis enim sem, a commodo risus. Nulla ullamcorper mollis vehicula. Sed in eros nec felis lacinia eleifend. Mauris quis lectus nisi, non dignissim neque. Quisque sem diam, laoreet ut commodo id, rutrum vitae magna. Morbi fermentum mollis tristique. Nullam in massa non mauris egestas imperdiet non non libero.</p>
        <p>Praesent egestas consequat rhoncus. Curabitur euismod sem faucibus lacus sollicitudin quis condimentum nibh congue. Integer semper auctor erat, ac condimentum neque suscipit sit amet. Cras ac porttitor velit. Aliquam eget auctor nunc. Nulla lacus orci, feugiat ac scelerisque vel, consequat vitae dolor. Duis felis neque, auctor vel eleifend id, gravida ut quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam feugiat posuere ligula, nec fermentum sem convallis sed. Cras hendrerit ante non lectus auctor posuere fermentum nisi congue. Sed adipiscing mi sed augue eleifend nec elementum ante lacinia. Aenean sem tellus, vulputate in imperdiet ut, blandit vel neque. Praesent luctus justo ac est lacinia non ultrices dolor adipiscing. Nunc molestie porta diam, rhoncus commodo est euismod non. Aliquam id nunc ac felis mattis viverra nec at tellus. Duis imperdiet leo sed massa bibendum convallis.</p>
        <p>Nam eu fermentum orci. Donec ullamcorper nulla quis magna vulputate nec vehicula nisi placerat. Integer ultrices sollicitudin metus, vitae porta metus tempus vitae. Pellentesque risus erat, lobortis et facilisis ac, ornare sit amet tortor. Nulla nunc ante, aliquet ut condimentum vitae, hendrerit ut dui. Vivamus in diam vel nisl feugiat gravida. Vestibulum vulputate ligula et ipsum dignissim at ornare felis porta. Nullam ante lorem, imperdiet eu bibendum et, feugiat eget mi. Nam vel nunc enim. Vestibulum a nibh leo, auctor dapibus ante. Praesent euismod, mauris at ultricies pretium, justo tellus pharetra dui, sed convallis dolor augue et erat. Donec scelerisque tempor feugiat. Vestibulum rutrum hendrerit ipsum non consectetur. Ut dui augue, consequat eu gravida tempus, pharetra et leo. Aliquam lacus mi, eleifend ut consectetur ut, iaculis in erat.</p>
        <p>Etiam a mi velit, nec elementum nibh. Morbi tempus suscipit augue, et auctor justo vulputate at. Morbi ac sem massa, quis consectetur velit. Duis quis augue arcu, et pellentesque libero. Integer a lorem sed mauris convallis dapibus. Sed id mollis sem. Ut augue magna, tempor consequat commodo sed, pharetra vel lacus. Aliquam erat volutpat. Pellentesque augue ipsum, consectetur ut dictum ac, tristique et lacus. Quisque nec gravida mi. Proin dignissim nisi vitae lacus feugiat sed feugiat nunc auctor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam a magna eget nibh gravida vehicula a eu nisl. Vestibulum elementum vulputate tristique. Mauris congue velit eget nulla luctus volutpat. Pellentesque scelerisque nunc id purus consectetur consectetur.</p>
        <p>Fusce quis arcu risus, at sodales quam. Proin et erat sem, quis tempor felis. Praesent varius faucibus felis vel scelerisque. Quisque venenatis iaculis interdum. Integer sagittis mollis risus, non ultricies erat suscipit nec. Nam cursus dignissim rutrum. Vestibulum ut imperdiet tellus. Praesent sem elit, pretium eu vehicula in, porttitor at magna. Etiam sit amet mauris massa. Donec massa lacus, commodo id aliquet non, tincidunt quis magna. Aenean ac dapibus mi. Vivamus sit amet quam vel nisi facilisis pellentesque sed vel sem. Nulla convallis, mauris eget viverra cursus, quam lacus egestas felis, eget tincidunt ante dui et erat. Nam id sapien purus, eget consequat sapien. Donec auctor vulputate velit, a rutrum diam faucibus ac.</p>
        <p>Phasellus lacinia nunc non diam ornare sodales. Sed cursus, enim id feugiat sagittis, massa enim suscipit sapien, id cursus eros purus ac nunc. Morbi eget neque libero. Fusce vel elementum magna. Duis sed lectus pellentesque arcu dignissim suscipit. Proin euismod aliquam convallis. In hac habitasse platea dictumst. Duis sit amet mauris id metus pretium eleifend vitae ac lorem. Phasellus auctor condimentum massa at consequat. Phasellus a nunc sem, id interdum orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris in nunc nibh.</p>
        <p>Aenean quis vehicula dui. Proin ut feugiat nisl. Mauris sit amet orci lectus. Quisque dictum congue condimentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin a velit sem, sed vehicula felis. Morbi consequat ullamcorper fermentum. Etiam libero ante, lobortis quis malesuada nec, porta et nisi. Sed euismod, dolor quis suscipit vulputate, odio dui varius tellus, nec fermentum metus mauris sed quam. Cras rutrum dignissim augue id fringilla. Nulla pellentesque luctus dolor ac ultricies. In imperdiet risus eget erat vestibulum nec tincidunt metus consequat. Nulla laoreet, dolor quis convallis ornare, leo mi egestas magna, at eleifend orci lectus eu velit. Pellentesque nec est at metus posuere commodo.</p>
        <p>Nam sit amet ligula sit amet est accumsan fermentum. In aliquam augue odio. Vestibulum at libero a libero varius molestie. In pharetra tellus et urna lacinia convallis. Nulla ultrices vestibulum odio dignissim ultricies. Phasellus condimentum, nunc a varius dictum, nisl quam vestibulum tellus, ut dignissim ante diam gravida nulla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris pellentesque eros et mi placerat ultrices. Cras pulvinar augue lorem, at mattis nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat. Nullam fermentum ipsum id eros semper eu malesuada felis ullamcorper. In hac habitasse platea dictumst. Proin lobortis aliquam nisi, vitae accumsan magna dictum sit amet. Morbi volutpat urna sit amet lorem hendrerit mattis.</p>
        <p>Vivamus in nisl massa, ut consequat purus. Donec quis nisl nunc. Praesent iaculis tristique molestie. Aenean hendrerit, diam non fermentum facilisis, felis ipsum pretium lorem, quis fermentum nunc nibh ac arcu. Suspendisse tortor tellus, egestas luctus iaculis et, venenatis vel diam. Aliquam ullamcorper leo lorem, eget sodales sem. Suspendisse et urna euismod felis tempus volutpat. Suspendisse quis metus ligula.</p>
        <p>Morbi bibendum eros hendrerit odio aliquam feugiat. Nam laoreet, arcu et sagittis molestie, nisl massa tempor lorem, quis tristique purus leo in libero. Fusce euismod, elit a ornare lacinia, enim velit ultrices diam, sit amet cursus nisi orci nec arcu. Donec sit amet tellus id dolor sodales ullamcorper sed at diam. In rutrum nunc vel eros tincidunt cursus. Fusce imperdiet quam et ante hendrerit auctor. Suspendisse suscipit augue eu dui auctor commodo. Nulla condimentum, turpis a pellentesque feugiat, urna augue blandit nulla, sit amet feugiat felis magna scelerisque augue.</p>
        <p>Aenean vehicula cursus turpis, id bibendum purus venenatis at. Mauris libero tortor, fringilla a luctus ac, placerat vitae mauris. Donec dictum orci et mauris euismod ultricies. Morbi vehicula posuere pellentesque. Aliquam eget metus ut diam consectetur fermentum. Aenean sagittis dapibus tortor at faucibus. Etiam tempor sem nec odio faucibus pharetra. Pellentesque consectetur tempus massa in bibendum. Curabitur adipiscing pulvinar dui vitae congue. Suspendisse ipsum sem, euismod quis condimentum vel, facilisis et nibh. Aenean nec tortor a elit tempor dictum in id justo.</p>
        <p>Ut ligula erat, pharetra ac bibendum quis, adipiscing sed nibh. Mauris sed nibh lorem, id tempor ipsum. Integer congue, nibh vitae sagittis lobortis, velit eros consectetur felis, a dignissim leo risus a enim. Proin bibendum tincidunt urna, non varius nunc euismod sed. Pellentesque et est at nibh varius commodo ac non augue. Donec ac nisl eros. Fusce at nisl est. Mauris sagittis volutpat varius. Aenean luctus cursus urna, eu tempor ligula ultricies nec. Proin aliquet ornare dolor, ac porta erat suscipit vel. Vivamus nec justo sem, sit amet tempor orci. Ut lorem nunc, viverra quis pellentesque eget, rutrum in urna. Nunc tristique, urna ut aliquam vestibulum, risus nisl molestie nisl, fermentum convallis ipsum dolor quis urna.</p>
        <p>Nunc id lobortis elit. Proin et lobortis risus. Pellentesque dapibus purus ac metus volutpat venenatis. Nunc condimentum, magna sed vulputate aliquet, leo nibh auctor urna, placerat lobortis quam magna a ante. Quisque varius, tellus sed dictum aliquam, sapien nunc ullamcorper odio, in consectetur libero nibh vitae eros. Quisque eget quam nec orci tempus sagittis nec non lorem. Mauris dolor massa, congue et mollis ut, mollis a nibh. Sed est purus, pellentesque vitae malesuada quis, pulvinar vel ipsum. Aliquam mauris dolor, malesuada nec sagittis eu, ullamcorper sit amet quam. Sed sed vulputate metus. Suspendisse et nulla libero. Nulla eros est, rutrum sit amet hendrerit et, viverra ac velit. Maecenas tempor, justo quis luctus semper, velit lorem fermentum ipsum, ac feugiat tellus dolor eu lectus. Pellentesque lobortis pretium eleifend. Curabitur a tortor nibh, sit amet semper dolor.</p>
        <p>Phasellus ut leo mollis purus ornare dapibus quis quis ipsum. Quisque mollis volutpat sem eget sagittis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed aliquet nibh id nisl porttitor at tempus odio mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras metus elit, venenatis et lobortis non, ornare eu neque. Curabitur eget risus non mi gravida blandit. Aliquam erat volutpat. Praesent tempus fermentum interdum. Pellentesque velit lectus, gravida non commodo in, sagittis ac tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti. Vivamus sollicitudin arcu leo.</p>

    </div>

</section>